#!/bin/bash


#Start
echo -e "Hello World \n"


#User and Host
Host=`hostname -f`
User=`id -un`

echo -e "Host : $Host ,  User : $User \n"


#Clock
Now=`date`
echo -e "Date : $Now \n"


#cwd
Shell_path=`pwd -P`
echo -e "Shell_path : $Shell_path \n"

#CLA

argc=$#
argv[0]=$0

i=1
until [ -z "$1" ]
do
        argv[$i]="$1"
        i=`expr $i + 1`
        shift
done

for ((i=0; i <= $argc ; i++))
do
        echo "$i = ${argv[$i]}"
done

echo -e "Argument count is $argc \n";

#DISK
usage=`df -k $1 | /bin/awk '{ rem = 0 } { n += 1 } { a = $3 } { b = $4 } \
        n == 2 { rem = int(a/(a+b) * 100); print rem} \
        END { }'`

if [ $usage -ge 80 ]


then
        echo "DISK($usage) - Warning"

elif [ $usage -ge 60 ]

then
        echo "DISK($usage) - Needs attention"

else
        echo "DISK($usage) - Safe"

fi

./shell

